name: Acceptance Tests and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: 🦄 Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install allure-pytest selenium chromedriver-autoinstaller

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: 🌟 Run Tests with Allure
        run: |
          mkdir -p allure-results
          pytest --alluredir=allure-results || echo "Some tests failed"

      - name: Debug Allure Results
        run: |
          echo "Debugging Allure Results Directory:"
          ls -R allure-results || echo "Allure results directory is empty"

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Allure Results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://github.com/allure-framework/allure2/releases/download/2.23.0/allure-2.23.0.zip
          unzip allure-2.23.0.zip -d /opt/allure
          sudo ln -s /opt/allure/allure-2.23.0/bin/allure /usr/local/bin/allure
          allure --version

      - name: Generate Allure Report
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)  # Create a unique timestamped directory
          allure generate allure-results --clean -o reports/$TIMESTAMP

      - name: Update index.html to Latest Report
        run: |
          LATEST_BUILD_DIR=$(ls -d reports/* | grep -oE '[0-9]+' | sort -n | tail -n 1)  # Get the latest build directory
          echo "<!DOCTYPE html><meta charset='utf-8'><meta http-equiv='refresh' content='0; URL=https://DinaButko.github.io/selenium-tests-resolver/reports/$LATEST_BUILD_DIR/'>" > reports/index.html

      - name: Debug Deployment Directory
        run: |
          echo "Contents of Deployment Directory:"
          ls -R
          echo "Contents of Reports Directory:"
          ls -R reports || echo "Reports directory is empty"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          force_orphan: true
